language: android
os:
  - linux
android:
  components:
    - build-tools-29.0.3
    - build-tools-28.0.3
    - android-29
  licenses:
    - 'android-sdk-license-e6a904e8'
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git
  - export PATH="$PATH:`pwd`/flutter/bin"
  - echo y | flutter doctor --android-licenses
script:
  - flutter pub get
    #- flutter precache
  - cd ./lib/
  - flutter analyze
    #- flutter build apk

after_script:
  - flutter clean

cache:
  directories:
    - flutter
    - $HOME/.pub-cache
