language: android

os:
  - linux

android:
  components:
    - build-tools-28.0.3
    - build-tools-29.0.3
    - android-29
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

stages:
  - name: deploy
    if: branch = master

before_install:
  - git clone https://github.com/flutter/flutter.git
  - export PATH="$PATH:`pwd`/flutter/bin"
  - yes | sdkmanager --update
  - yes | flutter doctor --android-licenses
  - flutter doctor -v

script:
  - flutter pub get
  - cd ./lib/
  - flutter analyze

before_deploy:
  - flutter precache
  - flutter build apk

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: m1+zsTWwOj5on//qdLoXzl4lWWixqk0eg410iXBbkKpPebAg1Wlo/A46qvzUvr+uqmxefsiFJQ5kPlL/SS3nS01p/7b4lGV857zP8DGgPPsoYx1aE1UDrlG7EWaJ4TVMymKyPbdfQDpKJJmTt8mB5xmm8TTRti52nJnpjGZBKTh3xhh7dwbbFQJcDII1iYUGFWxDYzSCgOaxYT/iFe2kR9hsQijjtRhxah7xcAqfoV2d0qzvLKe4sePBlL8qzAbaSAp+qVzsvfMNCK7OCyQuUo+muMRzQByH0O+8CuTb238N7J7Gi46KKBBGyOG5/wZONP3bst/OVK9OSPf3x4OiLTI9pT0HZIVb9/qYw+xmKgzDry13da3XMW6sGOZx/2MWbXyHtyZ/45X2feMYBm5rYn/IeuAUmbGkyuoopYCsXYHp4wVi50bbcn5033mfLfsyVsSySD+KKcerTXz06PdW4l5VU+1afdiyPxkGgfFp5DO/cbd0PR8Hk7/h0V+Oq9mvjuu4wp5WXq9ScJTBvOjux2bDdde6X59mbKjraOM5z3SaUjgaoACMvHG7PQHYvbvnCEmhtxM/zzFUeWjeU6CVSEoDBIv2fAz7qNpXxHFELT8EAgNp5x++Vx/C9IdsGPBdM3HI1vhwWXYCJp6q8Ad4q2tzRPcFuWRAkkO5lzNSXkE=
  file: build/app/outputs/apk/release/app-release.apk

after_script:
  - flutter clean

cache:
  directories:
    - $HOME/.pub-cache
